openapi: 3.0.3
info:
  title: 'Creppy Postcode Service'
  description: 'SnappyShopper - Code Test API Doc'
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/shops:
    post:
      summary: 'Add a new shop'
      operationId: addANewShop
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  id: 1
                  type: shop
                  attributes:
                    name: 'Bens Super Store'
                    latitude: 57.084444
                    longitude: -2.255708
                    status: O
                    maxDeliveryDistance: 100
                    createdAt: '2024-08-20T11:05:17.000000Z'
                    updatedAt: null
                  relationships: []
                  includes: []
                  links: []
                properties:
                  id:
                    type: integer
                    example: 1
                  type:
                    type: string
                    example: shop
                  attributes:
                    type: object
                    properties:
                      name:
                        type: string
                        example: 'Bens Super Store'
                      latitude:
                        type: number
                        example: 57.084444
                      longitude:
                        type: number
                        example: -2.255708
                      status:
                        type: string
                        example: O
                      maxDeliveryDistance:
                        type: integer
                        example: 100
                      createdAt:
                        type: string
                        example: '2024-08-20T11:05:17.000000Z'
                      updatedAt:
                        type: string
                        example: null
                  relationships:
                    type: array
                    example: []
                  includes:
                    type: array
                    example: []
                  links:
                    type: array
                    example: []
      tags:
        - 'Shops API endpoints'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'Must be at least 5 characters. Must not be greater than 100 characters.'
                  example: yesclauxqukxwnyjm
                latitude:
                  type: string
                  description: 'The postcodes latitude. Must match the regex /^[-]?(([0-8]?[0-9])\.(\d+))|(90(\.0+)?)$/.'
                  example: '57.084444'
                longitude:
                  type: string
                  description: 'The postcodes longitude. Must match the regex /^[-]?((((1[0-7][0-9])|([0-9]?[0-9]))\.(\d+))|180(\.0+)?)$/.'
                  example: '-2.255708'
                status:
                  type: string
                  description: 'The status. C for closed and O for open.'
                  example: O
                  enum:
                    - C
                    - O
                store_type:
                  type: string
                  description: ''
                  example: shop
                  enum:
                    - takeaway
                    - shop
                    - restaurant
                max_delivery_distance:
                  type: integer
                  description: 'Must be at least 0. Must not be greater than 100.'
                  example: 4
              required:
                - name
                - latitude
                - longitude
                - status
                - store_type
                - max_delivery_distance
      security: []
  /api/shops/search:
    post:
      summary: 'Search for shops within a specified distance (in miles).'
      operationId: searchForShopsWithinASpecifiedDistanceinMiles
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                example:
                  -
                    id: 1
                    type: shop
                    attributes:
                      name: 'Tesco Value Store'
                      latitude: 57.084444
                      longitude: -2.255708
                      status: O
                      maxDeliveryDistance: 100
                      createdAt: '2024-08-20T11:05:17.000000Z'
                      updatedAt: null
                    relationships: []
                    includes: []
                    links: []
                  -
                    id: 2
                    type: shop
                    attributes:
                      name: 'Reds Super Store'
                      latitude: 57.084444
                      longitude: -2.255708
                      status: O
                      maxDeliveryDistance: 100
                      createdAt: '2024-08-20T11:05:17.000000Z'
                      updatedAt: null
                    relationships: []
                    includes: []
                    links: []
      tags:
        - 'Shops API endpoints'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                postcode:
                  type: string
                  description: 'Must match the regex /^([Gg][Ii][Rr] 0[Aa]{2})|((([A-Za-z][0-9]{1,2})|(([A-Za-z][A-Ha-hJ-Yj-y][0-9]{1,2})|(([A-Za-z][0-9][A-Za-z])|([A-Za-z][A-Ha-hJ-Yj-y][0-9][A-Za-z]?))))\s?[0-9][A-Za-z]{2})$/.'
                  example: 'gIR 0aa|x2|vf98|K4t|vd3l)))3kG)'
                distance:
                  type: number
                  description: 'Must not be greater than 100.'
                  example: 16
              required:
                - postcode
      security: []
tags:
  -
    name: 'Shops API endpoints'
    description: ''
